
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
      - ./pdf:/app/pdf
    depends_on:
      - ollama

  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data: